image: debian:10.11

检查更新:
  only:
    - triggers
    - schedules
  stage: build
  variables:
    CI_DEBUG_TRACE: "false"
  #before_script:
    #- export
  script:
    - bash jobs/check_ver.sh
  #after_script:
    #- echo 3

ss-main:
  image: golang:latest
  rules:
    - if: $ss_main != 'false' && $ss_main_old
  stage: build
  script:
    - bash jobs/ss_main.sh

ss-tool:
  rules:
    - if: $ss_tool != 'false' && $ss_tool_old
  stage: build
  script:
    - bash jobs/ss_tool.sh

ipt2socks:
  rules:
    - if: $ipt2socks != 'false' && $ipt2socks_old
  stage: build
  script:
    - bash jobs/ipt2socks.sh

kcptun:
  image: golang:latest
  rules:
    - if: $kcptun
  stage: build
  script:
      - bash jobs/kcptun.sh

shadowsocks-rust:
  rules:
    - if: $shadowsocks_rust != 'false' && $shadowsocks_rust_old
  image: rust:latest
  stage: build
  script: bash jobs/shadowsocks_rust.sh

.BBRv2内核:
  #docker中编译内核的条件不满足，或者我没有找到方法先搁置。
  only:
    - triggers
    - schedules
  stage: build
  when: manual
  artifacts:
    paths:
      - /tmp/build/
    exclude:
      - /tmp/build/google-bbr/**/*
  script:
    - bash jobs/bbrv2.sh

测试运行:
  rules:
    - if: $update == 'true'
  stage: test
  script:
    - bash jobs/test.sh

后续整理工作:
  rules:
    - if: $update == 'true'
  stage: deploy
  script:
    - bash jobs/deploy.sh

清理编译记录:
  only:
    - triggers
    - schedules
  stage: deploy
  when: manual
  script:
    - bash jobs/clean_ci_log.sh

重置提交记录:
  only:
    - triggers
    - schedules
  stage: deploy
  when: manual
  script:
    - bash jobs/reset.sh
