image: debian:10.11

检查更新:
  only:
    - triggers
    - schedules
  stage: .pre
  variables:
    CI_DEBUG_TRACE: "false"
  before_script:
    - export
  script:
    - bash jobs/check_ver.sh
  after_script:
    - echo 3

ss-main:
  image: golang:latest
  rules:
    - if: $ss_main && $ss_main_old
  stage: build
  before_script:
    - bash jobs/push.sh
  script:
    - bash jobs/ss_main.sh

ss-tool:
  rules:
    - if: $ss_tool && $ss_tool_old
  stage: build
  before_script:
    - bash -x jobs/push.sh
  script:
    - bash jobs/ss_tool.sh

shadowsocks-rust:
  rules:
    - if: $shadowsocks_rust && $shadowsocks_rust_old
  image: rust:latest
  stage: build
  script: echo 456

BBRv2内核:
  only:
    - triggers
    - schedules
  stage: build
  when: manual
  artifacts:
    paths:
      - /tmp/build/
    exclude:
      - /tmp/build/google-bbr/**/*
  script:
    - bash jobs/bbrv2.sh

清理编译记录:
  stage: .post
  when: manual
  script:
    - bash jobs/clean_ci_log.sh
